// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.medical.clinic.bookingService;

public final class bookingProtoService {
  private bookingProtoService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_FreeDateRequest2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_FreeDateRequest2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_FreeDateReply2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_FreeDateReply2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_WithdrawRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_WithdrawRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbooking.proto\022\007booking\" \n\020FreeDateRequ" +
      "est2\022\014\n\004name\030\001 \001(\t\"!\n\016FreeDateReply2\022\017\n\007" +
      "message\030\001 \001(\t\"9\n\017WithdrawRequest\022\026\n\016acco" +
      "unt_number\030\001 \001(\005\022\016\n\006amount\030\002 \001(\0052\232\001\n\007Boo" +
      "king\022D\n\014askFreeDates\022\031.booking.FreeDateR" +
      "equest2\032\027.booking.FreeDateReply2\"\000\022I\n\021as" +
      "kFreeDatesAgain\022\031.booking.FreeDateReques" +
      "t2\032\027.booking.FreeDateReply2\"\000B:\n!com.med" +
      "ical.clinic.bookingServiceB\023bookingProto" +
      "ServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_booking_FreeDateRequest2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_booking_FreeDateRequest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_FreeDateRequest2_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_booking_FreeDateReply2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_booking_FreeDateReply2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_FreeDateReply2_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_booking_WithdrawRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_booking_WithdrawRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_WithdrawRequest_descriptor,
        new java.lang.String[] { "AccountNumber", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
