// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.medical.clinic.bookingService;

public interface FreeDateRequest2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.FreeDateRequest2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1 say variable one 2 variable two
   *string mario =2;
   *string lugi =3;
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * 1 say variable one 2 variable two
   *string mario =2;
   *string lugi =3;
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
