// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.medical.clinic.bookingService;

public interface FreeDateReply2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.FreeDateReply2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
