// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.medical.clinic.bookingService;

public interface WithdrawRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.WithdrawRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 account_number = 1;</code>
   */
  int getAccountNumber();

  /**
   * <code>int32 amount = 2;</code>
   */
  int getAmount();
}
